### ISSUE TITLE
elp eqwalize-all finding no files to analyze

### ISSUE THREAD

**Issue by tsloughter** [WhatsApp/erlang-language-platform#10]
### Describe the bug

```
$ elp eqwalize-all --rebar                                                    ─╯
o⠁ Loading build info                                                                Loading build info                                                                 Loading applications      ████████████████████ 58/58                               Seeding database                                                                   Compiling dependencies                                                             Gathering modules         ████████████████████ 203/203                           No files to eqWAlize detected
```

### To Reproduce**

Clone https://github.com/open-telemetry/opentelemetry-erlang and run `rebar3 upgrade --all` and `rebar3 plugins upgrade --all` (haven't upgraded the eqwalizer `main` yet because I'm trying to figure this out before bumping elp), then run `elp eqwalize-all --rebar`

Note the same happens for per-app runs:

```
$ elp eqwalize-app --rebar opentelemetry_api                                  
  Loading build info                                                                 Loading applications      ████████████████████ 58/58                               Seeding database                                                                   Compiling dependencies                                                           No files to eqWAlize detected
```

### Expected behavior

Expected analysis of all applications in the project.

### Actual behavior

No modules are analyzed

### Context

 - ELP Version (output of `elp version`): 1.1.0+build-2023-10-16
 - Editor used: None

**Comment by alanz** [comment]
There are two things affecting this.  

- The first is that the currently published version does not correctly run eqwalizer, due to an environment variable issue, fixed on master.
- The second is that the default is currently different for this version of `elp`, each file must be explicitly opted-in with a 
   `-typing([eqwalizer]).` attribute. We are looking at changing this to match the current eqwalizer behaviour

**Comment by tsloughter** [comment]
Thanks :+1:

**Comment by alanz** [comment]
I just checked current master (da0b80b04ab28e75ab1220398bfabc183d1f41fa) and it seems to work.

We will do a new release soon.

**Comment by alanz** [comment]
Please try again with [today's release](https://github.com/WhatsApp/erlang-language-platform/releases/tag/2023-10-26), and re-open if it is still a problem.
