### ISSUE TITLE
VSCode extension fails to start if `eqwalizer_rebar3` is not defined as `project_plugin`

### ISSUE THREAD

**Issue by javiergarea** [WhatsApp/erlang-language-platform#11]
### Describe the bug

Opening a project that does not include `eqwalizer_rebar3` as a `project_plugin` makes the VSCode extension fail when starting.

### To Reproduce

1. Install the VSCode extension from the marketplace (v0.7.0).
2. Open a project that does not include `eqwalizer_rebar3` as a `project_plugin`.

### Expected behavior

The extension should show a warning explaining that you will not get static typing analysis features while keeping the rest of them.

### Actual behavior

The extension fails and you don't get any of the functionalities.
```
ELP failed to switch workspaces:
Failed to read rebar build info for config file /foo/bar/rebar.config,
rebar 3.18.0 on Erlang/OTP 25 Erts 13.1.5:
cd "/foo/bar" && "rebar3" "as" "test" "build_info" "--to" "/var/folders/footmpfolder" failed,
exit status: 1 stdout:
===> Command build_info not found
```

### Context

 - ELP Version (output of `elp version`): v0.7.0 (VSCode Marketplace)
 - Editor used: VSCode

**Comment by alanz** [comment]
This already fixed on master, we are preparing a fresh release for later today.

**Comment by perehonchuk** [comment]
thanks @javiergarea for reporting. We plan to fix it soon

**Comment by perehonchuk** [comment]
Should be fixed by the latest release. Since we can't work without this plugin for rebar elp will display the error message and fallback to "no build system" mode (without dependencies). LMK if you have any issues
