### ISSUE TITLE
Using ELP without eqWAlizer

### ISSUE THREAD

**Issue by xxdavid** [WhatsApp/erlang-language-platform#14]
Hi!

Thank you so much for making ELP! I watched the talk about ELP at the last CodeBEAM with great interest. It sounds like this is going to be a great tool.

My question is: is it possible to use the ELP (especially the language server via the VS Code extension) without eqWAlizer. I believe eqWAlizer is a great tool, but I am not currently interested in using it (as I use Gradualizer, and some aspects differ between the two tools). I also understand that you always use the combo ELP + eqWAlizer internally in WhatsApp, but I think many people out there do not. I personally would appreciate all the code analyses that ELP alone brings (hovers, jump to definition, diagnostics, autocomplete etc.) but I don't want to see diagnostics/problems coming from eqWAlizer. Is there any way how I can configure my project or the VS Code extension to make ELP work like that?

**Comment by alanz** [comment]
You can disable it by puttin a file called `.elp.toml` in the root of your project, with the following into it

```toml
[eqwalizer]
enable_all = false
```

**Comment by robertoaloi** [comment]
I gave this a quick try and it looks like we currently don't have a way to combine a `.elp.toml` file with `rebar3` projects. The moment you create the TOML file, project discovery tries to use Buck2 to load project definition. We need to decouple the ability of running eqwalizer from the project discovery.

**Comment by alanz** [comment]
Please try this again with https://github.com/WhatsApp/erlang-language-platform/releases/tag/2024-01-29

We now separate out the config portion of `.elp.toml` and the project discovery part

**Comment by xxdavid** [comment]
Now it works as expected. Thank you! 🙁
