### ISSUE TITLE
elp panic!

### ISSUE THREAD

**Issue by garazdawi** [WhatsApp/erlang-language-platform#17]
### Describe the bug

thread 'main' panicked at /home/runner/.cargo/registry/src/index.crates.io-6f17d22bba15001f/text-size-1.1.1/src/range.rs:48:9:
assertion failed: start.raw <= end.raw
stack backtrace:
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
thread '<unnamed>' panicked at /home/runner/.cargo/registry/src/index.crates.io-6f17d22bba15001f/lsp-server-0.7.4/src/stdio.rs:29:37:
receiver was dropped, failed to send a message: "SendError(..)"
stack backtrace:
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.

Process erlang-language-platform stderr<2> finished

### To Reproduce**

Don't know, I was editing the io.erl file in Erlang/OTP and it crashed.

### Expected behavior

For the server to not crash :)

### Context

 - ELP Version (output of `elp version`): elp 1.1.0+build-2024-02-07
 - Editor used: emacs

**Comment by robertoaloi** [comment]
Thanks for reporting @garazdawi . Not sure how actionable is this from our side since it looks like one of the receiving ends just got killed. So this is the consequence, not the root cause. Anything else interesting in the logs that could help us investigating this further?

**Comment by garazdawi** [comment]
I'll check and see next time it happens. Unless there are some logs hidden somewhere that I could look at?

**Comment by robertoaloi** [comment]
Actually @michalmuskala  made me notice the ` start.raw <= end.raw` part, which suggests we're doing something wrong with byte spans.

**Comment by alanz** [comment]
Please report again with the new release, it should log a bit more context, which we can use to narrow down possibilities.
