### ISSUE TITLE
[feature request] make `elp eqwalize` accept multiple specific modules 

### ISSUE THREAD

**Issue by zerth** [WhatsApp/erlang-language-platform#21]
### Describe the bug

It would be nice if `elp eqwalize` accepted multiple specific module names as a middle ground between eqwalizing an entire app/project and single modules.  Rationale: I frequently need to eqwalize a set of modules involved in a series of commits, where those modules are either a tiny subset of an application having ~100 modules, or involve multiple apps in a larger project; I want to be able to quickly iterate on the most-relevant small subset before doing `elp eqwalize-app` or `elp eqwalize-all`.

### To Reproduce

```
elp eqwalize mod_a mod_b mod_c
```

### Expected behavior
`mod_a`, `mod_b`, and `mod_c` are eqwalized.

### Actual behavior

```
% elp eqwalize mod_a mod_b mod_c
No such command: `mod_b`, did you mean `--as`?
```

**Comment by robertoaloi** [comment]
Hi @zerth, thanks for raising this. @VLanvin @alanz does this make sense to you? Contributions are also welcome!

**Comment by VLanvin** [comment]
Makes sense, and I think this is a very simple change.
