### ISSUE TITLE
The location of the error warning is abnormal when use '\r\n'

### ISSUE THREAD

**Issue by misaki214** [WhatsApp/erlang-language-platform#22]
### Describe the bug

The location of the error warning is abnormal when use '\r\n'

### To Reproduce

-module(test).`\r\n`
`\r\n`
-export([test/0]).`\r\n`
`\r\n`
`\r\n`
`\r\n`
`\r\n`
`\r\n`
test() ->`\r\n`
    Test = 1,`\r\n`
    ok.`\r\n`

### Expected behavior

Report the correct location of the error.

#### use CRLF
![crlf](https://github.com/WhatsApp/erlang-language-platform/assets/81605435/64f45747-f317-4aa2-80c4-96a79d2bbfc0)

#### use LF
![lf](https://github.com/WhatsApp/erlang-language-platform/assets/81605435/5f222060-736f-404a-b126-02877d118056)

### Context

 - ELP Version (output of `elp version`): elp 1.1.0+build-2024-04-17
 - Editor used: vscode(wsl)

**Comment by alanz** [comment]
I just tried to reproduce this error, by putting a [test project file](https://github.com/WhatsApp/erlang-language-platform/blob/main/test_projects/linter/app_a/src/app_a.erl) into `CRLF` mode.  The locations continue to be correct, even after a complete VS Code restart.

<img width="531" alt="Screenshot 2024-04-22 at 11 32 13" src="https://github.com/WhatsApp/erlang-language-platform/assets/409607/bbed1c00-1c15-421b-8fd3-5202b62dbcf1">

And I have confirmed that it has `0d0a` as terminator.

**Comment by misaki214** [comment]
![image](https://github.com/WhatsApp/erlang-language-platform/assets/81605435/9932e076-fcdd-4da3-894e-b5ebf3ddb5b4)
Hi, @alanz. I reproduced the bug in [test project file](https://github.com/WhatsApp/erlang-language-platform/blob/main/test_projects/linter/app_a/src/app_a.erl).It needs multiple `\r\n` newline characters added at line 4.

**Comment by alanz** [comment]
Ok, I can reproduce that too.  And I see the unused function diagnostic comes from the erlang_service i.e. otp compiler.
