### ISSUE TITLE
No tooltip help on arguments of auto-imported BIFs

### ISSUE THREAD

**Issue by dszoboszlay** [WhatsApp/erlang-language-platform#29]
### Describe the bug

After typing the name of a function and an opening parenthesis, ELP provides some help on argument names and types in a tooltip:

![image](https://github.com/WhatsApp/erlang-language-platform/assets/1025306/da840ce8-8068-4ce3-b67c-07787e22b11c)

However, this doesn't work for auto-imported BIFs such as `register/2`, only when using a fully qualified function call syntax:

![image](https://github.com/WhatsApp/erlang-language-platform/assets/1025306/279dc086-186b-4d5f-a613-7d1fcbdb3794)

(Please also note that for whatever reason the tooltip shows as if `erlang:register` would exist with two different arities, while in fact there's only a single `erlang:register/2`, and both the 1/2 and 2/2 help messages look identical.)

### To Reproduce

In the body of a function type `register(`.

### Expected behavior

Auto-imported BIFs should show the same help message regardless of using the fully qualified function call syntax or not.

### Actual behavior

Auto-imported BIFs should only show any help message when using the fully qualified function call syntax.

### Context

 - ELP Version (output of `elp version`): `elp 1.1.0+build-2024-04-29`
 - Editor used: VS Code

**Comment by robertoaloi** [comment]
Thanks @dszoboszlay , I can reproduce. Adding to our backlog. In LSP terms, the feature is called [signature help](https://microsoft.github.io/language-server-protocol/specifications/lsp/3.17/specification/#textDocument_signatureHelp).

**Comment by alanz** [comment]
This is what I now get

<img width="934" alt="Screenshot 2024-05-23 at 16 13 25" src="https://github.com/WhatsApp/erlang-language-platform/assets/409607/140d1f07-fec4-4aba-9516-77fc4f1d9234">

**Comment by alanz** [comment]
And

<img width="767" alt="Screenshot 2024-05-24 at 15 23 54" src="https://github.com/WhatsApp/erlang-language-platform/assets/409607/e9ee5971-7a41-41a9-8503-76a435ce18e0">
