### ISSUE TITLE
build-info plugin was not installed.

### ISSUE THREAD

**Issue by Zabrane** [WhatsApp/erlang-language-platform#43]
Hi All

I'm using the latest `ELP` on macOS `Sonoma 14.5` (Intel arch) under VSCode `1.92.1`.
All working perfectly but I got this annoying warning related to **build-info** plugin.

![Screenshot 2024-08-11 at 02 30 22](https://github.com/user-attachments/assets/cf20ee27-e978-4a0f-b179-48c3749b4f30)
![Screenshot 2024-08-11 at 02 30 54](https://github.com/user-attachments/assets/f4c3107d-442e-4878-bf67-a303381e9ada)

My config:
```bash
$ elp version
elp 1.1.0+build-2024-04-17

$ rebar3 version
rebar 3.23.0+build.5383.ref6ce35057 on Erlang/OTP 27 Erts 15.0

$ erl
Erlang/OTP 27 [erts-15.0] [source] [64-bit] [smp:16:16] [ds:16:16:10] [async-threads:1] [dtrace]
Eshell V15.0 (press Ctrl+G to abort, type help(). for help)
```

A colleague of mine got the same warning on his macOS `M1`.

Help appreciated
Thanks

**Comment by robertoaloi** [comment]
Hi @Zabrane that means you don't have the `build_info` plugin installed. The plugin is currently necessary to automatically handle rebar3 projects. You can find the installation instructions [here](https://whatsapp.github.io/erlang-language-platform/docs/get-started/configure-project/rebar3/).

Alternatively, you can provide a custom configuration file as explained [here](https://whatsapp.github.io/erlang-language-platform/docs/get-started/configure-project/elp-toml/#build_info).

Let me know if this helps.

**Comment by Zabrane** [comment]
Thanks a lot @robertoaloi. 
After activating the debug-info module globally, the warning was gone.
