### ISSUE TITLE
Slack channel is inaccessible to non-Fiqus email addresses.

### ISSUE THREAD

**Issue by offsetcyan** [WhatsApp/erlang-language-platform#45]
### Describe the bug

Attempting to join the #elp Slack channel results in being told your account cannot be found in the Erlang workspace. Attempting to sign up to the workspace requires you have an @fiqus.coop email address.

### To Reproduce**

1. Attempt to sign-in with an unregistered email address.
2. Navigate to the account creation page ("create an account" on the top right of the page).
3. Attempt to register an account with the workspace.

### Expected behavior

I would be able to ask a support question in #elp.

### Actual behavior

I cannot access the workspace.

### Context

 - ELP Version (output of `elp version`):
 - Editor used:

**Comment by robertoaloi** [comment]
Hi @offsetcyan The #elp channel is part of the Erlang Slack. You can request an invitation by the Erlang Ecosystem Foundation [here](https://erlef.org/slack-invite/erlanger). Will update the description to reflect that (I have been a member of that Slack forever, so didn't recall you could not simply sign up). Thanks for raising this!

**Comment by robertoaloi** [comment]
Added a reference [here](https://github.com/WhatsApp/erlang-language-platform/commit/f1ed1572ff10d72e655baec5121f796a4cf0004c)
