### ISSUE TITLE
Please add erlang_ls.config support and/or erlang.mk, bazel

### ISSUE THREAD

**Issue by deadtrickster** [WhatsApp/erlang-language-platform#5]
Hi, congratulations with the first public release!

I tried it with RabbitMQ where we use erlang.mk and bazel and erlang_ls successfully. Well it complains about missing rebar.config. 

Please consider relaxing requirements and having erlang_ls.config support (here we list all the paths).

Thank you for improving Erlang world.

**Comment by alanz** [comment]
We will be devoting some time to doing this soon.

**Comment by deadtrickster** [comment]
😭

**Comment by robertoaloi** [comment]
@deadtrickster Let me check the internal status of this and come back to you.

**Comment by alanz** [comment]
@deadtrickster We can now load a build_info.json file describing the project setup.
Instructions are at https://whatsapp.github.io/erlang-language-platform/docs/get-started/configuration/.
This should hopefully enable some sort of progress for you.

We will be enabling buck2 support in the standard release soon too, just sorting out getting the tests to pass on the repo.
Note: you can build a version from source, leaving out `--no-default-features` when you build it, and it will work against buck2 projects. We just can't pass CI yet.

**Comment by robertoaloi** [comment]
> @deadtrickster We can now load a build_info.json file describing the project setup. Instructions are at https://whatsapp.github.io/erlang-language-platform/docs/get-started/configuration/. This should hopefully enable some sort of progress for you.

Instructions have been moved to https://whatsapp.github.io/erlang-language-platform/docs/get-started/configure-project/custom-project/

**Comment by ikavgo** [comment]
Thank you!

**Comment by robertoaloi** [comment]
@ikavgo I added a mechanism that will simplify this even further. Pushing the change as we speak.
I already tested it with the `rabbitmq-server` repo.

**Comment by robertoaloi** [comment]
This is now available via 2957db5c16eaef9e4c41f1cb84acead9230eb0ef (release coming). I pull requested a working config for `rabbitmq-server` [here](rabbitmq/rabbitmq-server#11250). Closing this as done.
