### ISSUE TITLE
breakpoint not supported?

### ISSUE THREAD

**Issue by ziyouchutuwenwu** [WhatsApp/erlang-language-platform#50]
hi, i use vscode with elp plugin as erlang editor.

i can not set breakpoint on erl file, and when i press f5, vscode told me like this

![image](https://github.com/user-attachments/assets/8dff1004-4e9a-4d04-ad29-42abe96c4910)

is there any plan to support breakpoint?

**Comment by robertoaloi** [comment]
Hi @ziyouchutuwenwu 

The extension does not have support for debugging, yet, but it should be trivial to add (reusing the same debugger as Erlang LS). Keep in mind that the debugger is based on the OTP interpreter, so it has many limitations (in both extensions).

**Comment by ziyouchutuwenwu** [comment]
thank you very much!
