### ISSUE TITLE
Documentation-on-hover support for new OTP27 doc attributes

### ISSUE THREAD

**Issue by NelsonVides** [WhatsApp/erlang-language-platform#54]
### Describe the bug

When hovering over function calls, documentation-on-hover shows information only if the documentation was written in the older edoc format, but not in the newer OTP27 doc attributes.
 
<img width="136" alt="image" src="https://github.com/user-attachments/assets/7d2f35bb-d2ca-4eea-a5e6-b469f4e8b429"> <img width="171" alt="image" src="https://github.com/user-attachments/assets/101a0a9e-f815-4e42-9586-926287626135">

### To Reproduce**

In the following code:
```erlang
%% @doc this is edoc
edoc_dummy() ->
    ok.

-doc """
This is a doc attribute
""".
docattr_dummy() ->
    ok.

callers() ->
    ?MODULE:edoc_dummy(),
    ?MODULE:docattr_dummy(),
    ok.
```

### Expected behavior

I'd expect both documentation types to display on hovering.

### Actual behavior

`edoc_dummy/1` hovering displays the edoc information, but `docattr_dummy/1` does not.

### Context

 - ELP Version (output of `elp version`): elp 1.1.0+build-2024-08-05
 - Editor used: neovim

**Comment by robertoaloi** [comment]
@NelsonVides This is correct. Support for OTP 27 style EDoc is not added yet (but it's planned).

**Comment by robertoaloi** [comment]
This is now available in [2024-11-07](https://github.com/WhatsApp/erlang-language-platform/releases/tag/2024-11-07).
