### ISSUE TITLE
I am running CentOS 7 x86_64 system with OTP version 19, can I compile the latest version of elp?

### ISSUE THREAD

**Issue by imLaoYang** [WhatsApp/erlang-language-platform#58]
I am running CentOS 7 x86_64 system with OTP version 19, can I compile the latest version of elp?

**Comment by robertoaloi** [comment]
Hi! Unfortunately not, we recommend running ELP with Erlang/OTP 26 or higher.

Note: Erlang/OTP 19 was released in January 2019. If you are still using it, you may want to consider upgrading to a more recent version.
